const Funcionalidades = {
  VISUALIZAR_ESTOQUES: 1,
  EDITAR_ESTOQUES: 2,
  EXCLUIR_ESTOQUES: 3,
  VISUALIZAR_MOVIMENTACOES: 4,
  DAR_ENTRADA_ESTOQUE: 5,
  DAR_SAIDA_ESTOQUE: 6,
  INATIVAR_PRODUTOS_ESTOQUE: 7,

  VISUALIZAR_PRODUTOS: 8,
  EDITAR_PRODUTOS: 9,
  EXCLUIR_PRODUTOS: 10,

  VISUALIZAR_REVENDEDORES: 11,
  EDITAR_REVENDEDORES: 12,
  EXCLUIR_REVENDEDORES: 13,

  VISUALIZAR_CONFIGURACOES: 14,

  VISUALIZAR_FUNCIONALIDADES: 15,
  EDITAR_FUNCIONALIDADES: 16,
  ATIVAR_FUNCIONALIDADES: 17,
  INATIVAR_FUNCIONALIDADES: 18,

  VISUALIZAR_PERMISSOES: 19,
  EDITAR_PERMISSOES: 20,
  ATIVAR_PERMISSOES: 21,
  INATIVAR_PERMISSOES: 22,
  ASSOCIAR_FUNCIONALIDADE_PERMISSAO: 23,

  VISUALIZAR_PERFIS: 24,
  ATIVAR_PERFIS: 25,
  INATIVAR_PERFIS: 26,
  ASSOCIAR_PERMISSAO_PERFIL: 27,

  VISUALIZAR_USUARIOS: 28,
  EDITAR_USUARIOS: 29,
  ASSOCIAR_PERFIL_USUARIO: 30,
  ATIVAR_USUARIO: 31,
  INATIVAR_USUARIO: 32,
  ASSOCIAR_REVENDEDOR_USUARIO: 33,
  VISUALIZAR_TODOS_ESTOQUES: 34,
  VISUALIZAR_DASHBOARD: 35,
};

export default Funcionalidades;
