// <auto-generated />
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations.ApplicationDbContextMasterMigrations
{
    [DbContext(typeof(ApplicationDbContextMaster))]
    [Migration("20250515163626_TabelaClientUsuario_Correcao")]
    partial class TabelaClientUsuario_Correcao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CWCliente", b =>
                {
                    b.Property<int>("nCdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdCliente"));

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<bool>("bFlAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("sNmCliente")
                        .HasColumnType("text");

                    b.HasKey("nCdCliente");

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWClienteUsuario", b =>
                {
                    b.Property<string>("sCdUsuario")
                        .HasColumnType("text");

                    b.Property<int>("nCdCliente")
                        .HasColumnType("integer");

                    b.HasKey("sCdUsuario");

                    b.HasIndex("nCdCliente");

                    b.ToTable("CLIENTE_USUARIO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWClienteUsuario", b =>
                {
                    b.HasOne("Domain.Entities.CWCliente", "Cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("nCdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.CWCliente", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
